project_id = "cuyfrpuiokvqvhvoerga"

[functions.get-system-metrics]
verify_jwt = false

[functions.discover-agency-links]
verify_jwt = false

[functions.mp-create-subscription]
verify_jwt = false

[functions.mp-create-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.scrape-property]
verify_jwt = false