// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urzoecuaknwlxzhpuyrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyem9lY3Vha253bHh6aHB1eXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NDY3NTYsImV4cCI6MjA4NzEyMjc1Nn0.6BqAI0uedwTwVve27oAAmNsePo9UwhkHWB9eQAP3Dmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});