// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuyfrpuiokvqvhvoerga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1eWZycHVpb2t2cXZodm9lcmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NDgxMjUsImV4cCI6MjA5MDAyNDEyNX0.ErCSJvCwcI24b3GG-ZYvq29XCV27wN1mxvO6Uk3ocac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});