// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktayllrmzoocgxhwyurv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0YXlsbHJtem9vY2d4aHd5dXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NDY2MTcsImV4cCI6MjA4OTEyMjYxN30.0IWrD6weavq7FOCocBlOwP3ianaKZS8xHeX1wM9EFho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});